### PR TITLE
WIP improve project infrastructure

### PR DESCRIPTION
**Pull request by vojtechszocs**
Work in progress.

- `yarn dev` for development build
- `yarn dev-server` to start webpack dev-server
- `yarn build` for production build
- `yarn storybook` to start Storybook server

Using webpack 4 and Babel 6. Trying to keep webpack config clean and minimal.

Not using Babel 7 since the dependant projects (like Storybook) haven't adapted yet to the new `@babel/foo` scheme in terms of peer dependencies. Once we upgrade to Babel 7, we'll put all Babel related config to `babel.config.js` right next to webpack config.

Trying to keep root directory clean, all build/tool configuration lives in `config` directory.

Not using `whatwg-fetch` since all our target browsers already support this API (see `targetBrowsers` in webpack config).

Using `A.x` or possibly `A.B.x` semver ranges instead of `^A.B.C` to make version assumptions more apparent. (This convention was taken from `openshift/console` project.)

There are currently some un-avoidable `unmet peer dependency` warnings. All of them come from `patternfly-react` and all of them are irrelevant for us, i.e. pulled in through optional dependencies.

Supported browsers are the same as in `openshift/console` project: latest version of Chrome, Firefox, Edge and Safari. You can also see our current target browsers when running `yarn dev`.

Using `babel-polyfill` instead of ["ponyfills"](https://github.com/sindresorhus/ponyfill) which are better suited for libraries. We own the whole HTML page, we don't care if the polyfill mutates the globals.

Supported Node.js versions declared in `package.json`: it's either v8 (current active LTS) or v10 (upcoming LTS).

### CODE REVIEW

**Comment by vojtechszocs** [comment]
cc @ohadlevy @jelkosz @rawagner @mareklibra

**Comment by vojtechszocs** [comment]
Hmm, all files appear as newly added, I think I messed up something. Next time, I'll rebase on top of recent master.

**Comment by rawagner** [comment]
@vojtechszocs webpack config looks good. But please rebase on top of the master so we can see the actual changes.

**Comment by ohadlevy** [comment]
@vojtechszocs I believe that based on #22 this PR can be closed?

**Comment by mareklibra** [comment]
@vojtechszocs , #22 landed, can we close this one? We can still use bits from here for follow-ups.

**Comment by mareklibra** [comment]
Closing in favor of #26.

**Pull request closed without merging**
