### PR TITLE
Fixed css issue with top projects card

### PR DESCRIPTION
**Pull request by gnehapk**

### CODE REVIEW

**Comment by ohadlevy** [comment]
just wondering, whats the issue you are trying to solve? (maybe before / after screenshot can help?)

**Comment by cloudbehl** [comment]
@ohadlevy if you see the width of the line(openshift-storage) in the graph. It is different from the width of default namespace storage. So the line is getting cut because of some padding issue.
Screenshot from 2019-04-22 11-14-41

@gnehapk can you paste after picture of the graph.

**Comment by cloudbehl** [comment]
Depends: https://github.com/kubevirt/web-ui/pull/325

**Comment by gnehapk** [comment]
@ohadlevy After fixing, it looks like - 

top-projects-card

**Pull request merged**
