### PR TITLE
Change PVC access mode to RWM

### PR DESCRIPTION
**Pull request by rawagner**
backport of https://github.com/kubevirt/web-ui-components/pull/495

https://bugzilla.redhat.com/show_bug.cgi?id=1719134

### CODE REVIEW

**Comment by rawagner** [comment]
Bug is not yet approved for backporting, so do not merge please

**Comment by mareklibra** [comment]
@rawagner , what is the blocker for merge here?

**Comment by jelkosz** [comment]
@mareklibra nothing technical, it just needs to be decided that it should be targeted to 2.0. Will update here once the https://bugzilla.redhat.com/show_bug.cgi?id=1719134 has the correct flags

**Comment by jelkosz** [comment]
@mareklibra now the BZ is targeted to 2.0, you can merge :)

**Comment by jelkosz** [comment]
/hold
@mareklibra wait for it :) Maybe we should not merge this afterall, we would break the local storage use case with this.

**Comment by mareklibra** [comment]
Per agreement, this is ready to land.

**Pull request merged**
