### PR TITLE
Utilization: Add Disk Usage chart

### PR DESCRIPTION
**Pull request by mareklibra**
and refactor prometheus queries for disk capacity so they
can be reused for utilization.

### CODE REVIEW

**Comment by mareklibra** [comment]
In the memory/storage utilization charts, the `total` is used as maximum for Y-axis.

If `total` is much higher than actual consumption, the chart does not show "progress" vividly as the consumption is nearly to be a constant.

What about using
- maximal historic value (from the given range) as Y-axis maximum
- but units (KiB, TiB, etc) from the `total`?

What others think?

**Comment by rawagner** [comment]
I would vote for using value AND units from max historic value

**Comment by mareklibra** [comment]
And yet another (better) possibility handling the case with "almost constant" values within the range:
For max-y, use max historic value multiplied by 2 or cluster's capacity total, whatever is lower.

This approach handles:
- near-constant values
- values `<<` total

**Comment by suomiy** [comment]
+1

**Pull request merged**
