### PR TITLE
refactor selectors

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by jtomasek** [comment]
Since we're doing the refactoring, aren't we overloading `utils/` here? Why not putting the selectors directly under `src/` ?

**Comment by suomiy** [comment]
I guess they could be under `src` because they are quite important part of the application

**Comment by suomiy** [comment]
rebased and moved to `src`

**Comment by suomiy** [comment]
rebased, @rawagner @mareklibra can we go forward with this patch?

**Pull request merged**
