### PR TITLE
Prettier: allow trailing commas

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by mareklibra** [comment]
I like this. But as this is a matter of preference, let's see what others think too.

**Comment by pcbailey** [comment]
Personally, I don't use trailing commas, but I also don't have a strong opinion on the issue, either way. So, I'm good with whatever the majority decides.

**Comment by rawagner** [comment]
Im fine with merging

**Comment by vojtechszocs** [comment]
With trailing commas, the diff can be smaller, so I'm OK with having them.

If we do so, let's stay consistent with our comma usage.

**Pull request merged**
