### PR TITLE
Do not close Create VM Wizard when clicked outside of modal

### PR DESCRIPTION
**Pull request by rawagner**
https://bugzilla.redhat.com/show_bug.cgi?id=1710888

### CODE REVIEW

**Comment by suomiy** [comment]
IMO this is a feature, not a bug :) Users should know what to expect from `escape` key.

**Comment by suomiy** [comment]
not sure about the backdrop click

**Comment by mareklibra** [comment]
I like this change.
Former behaviour was annoying to me.

**Comment by andybraren** [comment]
No other modal (that I can find) closes itself when clicking on the backdrop, so I agree that annoying behavior should be changed. 🙂

I'm not sure about disabling the `Esc` key though. The new [PF4 wizard](https://www.patternfly.org/v4/documentation/react/components/wizard/) supports using `Esc` to close for accessibility reasons I believe, and existing modals within the Console can be `Esc`'d to close too. Is hitting `Esc` and accidentally closing the modal a frequent problem?

**Comment by matthewcarleton** [comment]
+1 to @andybraren comment about the "esc" key. For more information: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html and here's a good write up on it too https://simplyaccessible.com/article/closing-modals/

**Comment by rawagner** [comment]
@andybraren @matthewcarleton thank you for the input! I changed it to not close when user clicks outside of modal (which was pretty annoying), `esc` is unchanged.

**Pull request merged**
