### PR TITLE
Add configurable URL Disk size

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
dv_size

**Comment by lizsurette** [comment]
> default value is 10G, user can edit it if he wants. Field allows entering only positive number.
> 
> @jelkosz @lizsurette @mareklibra

@rawagner Would the user be able to see this as a disk and edit the size in the Storage step, too?

**Comment by rawagner** [comment]
@lizsurette no. It will show only in Basic Settings step. But I plan to reimplement this for 1.4. We will have ability to create disk (not just attach it) so I will require, in case of URL image source, that user will create at least one disk.

**Comment by lizsurette** [comment]
> @lizsurette no. It will show only in Basic Settings step. But I plan to reimplement this for 1.4. We will have ability to create disk (not just attach it) so I will require, in case of URL image source, that user will create at least one disk.

@rawagner Sounds great! Thanks for explaining :)

**Pull request merged**
